name: Build yanic.deb
on:
 - push
 - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: golang:bookworm

    steps:
      - uses: actions/checkout@v6
      - name: Prepare makedeb
        run: |
          apt update
          apt install sudo
          # Setup makedeb user
          useradd -m makedeb
          echo 'makedeb ALL=(ALL:ALL) NOPASSWD:ALL' >> /etc/sudoers
          chown -R makedeb:makedeb .
      - name: Install makedeb
        run: |
          wget https://github.com/makedeb/makedeb/releases/download/v16.1.0-beta1/makedeb-beta_16.1.0-beta1_amd64_jammy.deb
          dpkg -i makedeb-beta_16.1.0-beta1_amd64_jammy.deb || apt --fix-broken install -y
      - name: Build deb
        run: |
          su makedeb <<EOF
            makedeb --no-confirm --no-deps
          EOF
      - name: Upload deb artifact
        uses: actions/upload-artifact@v7
        with:
          archive: false
          path: yanic_*.deb
