name: Build yanic.deb
on:
 - push
 - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: golang:buster

    steps:
      - uses: actions/checkout@v3
      - name: Build deb
        run: ./build.sh
      - name: Upload deb artifact
        uses: actions/upload-artifact@v3
        with:
          name: yanic
          path: out/yanic_*.deb
